apiVersion: v1
kind: Secret
metadata:
    name: incident-commander-postgres
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:VppsP6x+9Gpuy1iwiDa50swD4hKP4qERGcOXAI+7jRmx66RucU/fClIGPS3iSiek1mUu9uBVIMPiX0RMy9SW8zJYPbGiYvG5wmVOMDBjIyuG9g==,iv:t6UN5VgZkg9Mh865Mdqfra7lgUBf9IJ/oC24iikD9yI=,tag:RBnWLj2YIZZT808hzLbOhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWh2VUsvOEhLWDBURC83
            cEFJRmhRRk0zMTJDNUZSNHpZZ3R3Ty8zOFYwCm1UZlZ1RXNkanNjUjRabno4c0w1
            S25hWFlXOEdlRGVSK2NrV2o2eExJVU0KLS0tIFVPclY0eVZvaGtIcVhTdHJVNXlq
            dmlhNEgrSGcyUzJLM3luMWJNU0djNGsK6aJT7MBXIkDjuOrcejassEWcAm8D0GqY
            aeiriUhLYx7br5FYixqdAs0hyCb92+qhNSqlzve5KrxrOW4ENN2d3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T07:03:01Z"
    mac: ENC[AES256_GCM,data:JXUPykUM4X9Wdww9czKDbvcwwxb0vWfQZvUxE3LlUZ3HHu8euV7tjE/kajwAZDcQEq52IM9zAUjz6r2HNKpO2nVe/ufB6F//d2uDXpURPiexTCf88mf/ZBhNczhsCnYc83KSlLP5W90FqS5/bvMBtUHiyufxZS88+28DiWlRWtc=,iv:1/6Lka0MW55XGRORTlx9P2AsZvpBM+FccgXhTX5CCIM=,tag:iuQJfHyoVVzLbVwNOnLoSA==,type:str]
    version: 3.13.2
