---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: 'true'
        statefulset:
          volumeClaimTemplates:
            - name: alertmanager
              accessMode: ReadWriteOnce
              size: 256Mi
              storageClass: longhorn
              globalMounts:
                - path: /alertmanager
        pod:
          securityContext:
            fsGroup: 65534
            runAsUser: 1000
            runAsGroup: 1000
        containers:
          alertmanager:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.32.1
            ports:
              - name: http
                containerPort: 9093
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M
        defaultContainerOptionsStrategy: merge
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
    service:
      main:
        controller: main
        ports:
          http:
            port: 9093
    persistence:
      config:
        enabled: true
        type: configMap
        name: alertmanager-configmap
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        enabled: true
        type: secret
        name: alertmanager
        globalMounts:
          - path: /etc/alertmanager/secrets
            readOnly: true
    route:
      main:
        hostnames:
          - alertmanager.${HOMELAB_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
