---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: investment
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          investment:
            image:
              repository: ghcr.io/adityathebe/investment
              tag: 1.1.1
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host 'investment.${HOMELAB_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
