apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
stringData:
    admin-password: ENC[AES256_GCM,data:wmWZqwdgF6AVqw6j+uHryFjzpiXa9wXlQ4MMFhTybFFy0NIM6JAi1H1EDIc=,iv:Lu3lJkMoSHqnerH/KB7HHUapX8ymiKtgXwugZGglHmw=,tag:KxV4X9fj+5T6b96qDcVP6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcDFiMitXWER6ckVPVXJD
            YjRXV1NhdEV0c1BhS1MyVFhwUDE0VDFHc1NNCjBTeGsyOW1mVmsvSWVJM2xNWjh3
            QnVwVlhVN1NtMjhka1pWZDliaVBKREEKLS0tIDlNUUt2OXpnV2pYRWNlUVNvczY2
            cm9qUXl6NUZ5VHBoVjBhVUI1SXBSKzQKLkVNxqw16NSX0L8cekAEj66aJWCJ195F
            oUF/lKUSVSwKwdrKNIrXBjXa/8wjkJkA1JKzQDAq5f6JyKQZyODlHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T08:44:47Z"
    mac: ENC[AES256_GCM,data:gWS6sbozMOAjK2Xbdbij2J1WQZIgQT5n4xqcJ6nAuYSbPVja4yeRC37sdOrbmYP1g+Hmn8u6yhva5b7KFuZA5Eqe4vWXo5PUrbqjOrDb7UntUbSWqD+PVhO1j6wwjiFHk85O6bhXW8k+Oc2YAjEsXDrxnLR9Fj+lgWAIs7WmUXg=,iv:sRmaN9xnLPVL/yQgoPTQ4WMXRUrfDyticeRLW+RG22g=,tag:4qBgafoZMZnewlXBqpzuow==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PIKL9V2OLk4=,iv:bd1YJ6ryo3nV1sHHoieRTGeQ/dw7A6zoN3Ruh3EuccM=,tag:3kRT1ySia8r3ISz6CkCqrg==,type:str]
    password: ENC[AES256_GCM,data:Ze7S1c3QVs1GyFaxbVlstH/7nNSjfcxGqMA4HtDapdkh4biAzR1wvXCqZRo=,iv:Wym4/rR4La/1o0dG959WtB6WVKUyjrj8IBCzA3AkweI=,tag:6ND2NQPdp0NVkPMRuj1ZSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcDFiMitXWER6ckVPVXJD
            YjRXV1NhdEV0c1BhS1MyVFhwUDE0VDFHc1NNCjBTeGsyOW1mVmsvSWVJM2xNWjh3
            QnVwVlhVN1NtMjhka1pWZDliaVBKREEKLS0tIDlNUUt2OXpnV2pYRWNlUVNvczY2
            cm9qUXl6NUZ5VHBoVjBhVUI1SXBSKzQKLkVNxqw16NSX0L8cekAEj66aJWCJ195F
            oUF/lKUSVSwKwdrKNIrXBjXa/8wjkJkA1JKzQDAq5f6JyKQZyODlHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T08:44:47Z"
    mac: ENC[AES256_GCM,data:gWS6sbozMOAjK2Xbdbij2J1WQZIgQT5n4xqcJ6nAuYSbPVja4yeRC37sdOrbmYP1g+Hmn8u6yhva5b7KFuZA5Eqe4vWXo5PUrbqjOrDb7UntUbSWqD+PVhO1j6wwjiFHk85O6bhXW8k+Oc2YAjEsXDrxnLR9Fj+lgWAIs7WmUXg=,iv:sRmaN9xnLPVL/yQgoPTQ4WMXRUrfDyticeRLW+RG22g=,tag:4qBgafoZMZnewlXBqpzuow==,type:str]
    version: 3.13.1
