apiVersion: v1
kind: Secret
metadata:
    name: fern-admin
    namespace: default
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:WGzKgBo=,iv:pixZTelIDJr8fEXzoB49sJcSgPD2vbP/NRN/kWCHCSU=,tag:UfbWo0eeL34DlasdtzLnBw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:7TGEgih8dONYcpU7qzHp0m30mq32qSE2j1TKHNOnMC0=,iv:99Fg/LVLO8qS5F1Kq61TfGodOV2m532GHGWyCcpycug=,tag:hg1DpGrJrvv1N/05/3DUnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcUdZWW9jS2VvSk15WGdt
            cU13RnZRM1g5MGl0bG8vMXdrWHNNV2tldkJZCnJjT0lydEV3ZkpLV1A3blp5VmhV
            QU9ScW8ydjc1SlBDMGkza2N4c21wV28KLS0tIFI2VDl2RDZacGxJZExDSThGWU8x
            c1BOdTR1NWxMMlcwTmlSVVVicUVKRmsKsXXit3uiZoY3rvbWtbdAJNvRJRigLRQK
            23OkpAyGg0ibKs8dUvxwy8KJBeCmZJ8gAps5hCqn7ixR2lTH7rnI7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T16:37:12Z"
    mac: ENC[AES256_GCM,data:sfDJj13AF3CvYsTqmM3LkAMgvFNYHBET4TXROiajYYxfw1YLNFlnolnI9EwaPt5vKQg8GQ/w/GQrm6gvW85PGX+ij1AGZHTAZLyXetUuyE+88Nnkj+ORW+4U68Qu9o+cbgZlQp3f+eaQ5SJD4j9PhZ50ywzKcDTsJOa4KU/UaXM=,iv:nDJJVJeC7G6JNPekPVdj2samCJFWoijHj7vjue8GjGg=,tag:OBk5o4Ydl1cEcNPBC6EPtA==,type:str]
    version: 3.13.2
