apiVersion: v1
kind: Secret
metadata:
    name: fern
stringData:
    PUBLIC_URL: ENC[AES256_GCM,data:vsqBUfvPTAA9jTankvLwiLjqj6K0OEKA,iv:P3wnTuxT2htsuwxEG/Ha9pvvKVWdQD2Zw7Nl+RGVQjY=,tag:3MjbpiM2seDiSuFpYO2Gtw==,type:str]
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:gwxU7OYCzxwZEOu5sGRgLZQTrLkzMs01DD4/M0g2LhUNEKdHCrnRiMNBO90vJw+CW0zp9KNZE/dqRwKT9QO9VuNKEF2YRAIA,iv:BpcawMNbadhpkSNdYozs1IyVwegmiZitIUbhQwK6MI0=,tag:z8xbfl3RVDArjk54XRFLZg==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:GhNY5Yduu7BlLoRjnpZMKm6OP7CZ3QJ1l3/hGrU/EYK1jB0=,iv:ixa7vq148BlJXQzvr75wb+Gvg78SG2AXM5XfkZ1H82g=,tag:O6u1iYqShhLaZ7MAyvZM6w==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:tsAuBx3x4J4W9W3Rw1Q2uh3kyeuBKY78HbM=,iv:FBk1fESWKNJ74BEF4SBC0IY4wHt4fsLqTYVVO/ntf5s=,tag:xRmZWQba4kOw1guTNrtWgA==,type:str]
    EMAIL_REPLY_TO: ENC[AES256_GCM,data:vtE7df2bsHmPWGNuJLHFhEsPVg==,iv:rz2pQU9z3kOexsbMPmKDaB49I7PQNFAe0SDj8DfFKbo=,tag:dp3paU9+Z927PvgD+GowCA==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:lNHKJCm5XlgTb9E8cBfEr35IJb/Xvi33TTZPP7hdA4JRUSE2,iv:u1qk+zbW0f9vM58YO1QJFvddNW6nYQSzEheB9AGhwjA=,tag:vJg841+ufJAgeO4Ayv+6bw==,type:str]
    ASSET_STORAGE_BACKEND: ENC[AES256_GCM,data:wlY=,iv:AApAI3tGrGN7LVvd1Q24PSYXwh2lH4JlN1C84i0x+3Y=,tag:bC+bUtUplsmGbCXI0r6BNg==,type:str]
    ASSET_STORAGE_S3_BUCKET: ENC[AES256_GCM,data:idGG2Q==,iv:aOYFmNMRv4hiuBSryJiQGstJBdmVlCnsfUcyrhQ9uEQ=,tag:li/aqwI67JCbxKMcDkV+PQ==,type:str]
    ASSET_STORAGE_S3_REGION: ENC[AES256_GCM,data:oa2EEO0n8XYP,iv:Q2kNrev9xkXs+R/Qdn0PtqaiQ1Ai1ABOdUD0sVKUxwA=,tag:rE7Zcith36YDS7dkua18Dw==,type:str]
    ASSET_STORAGE_S3_ENDPOINT: ENC[AES256_GCM,data:KzVR9Avqbin7JglUbap8XDwZwwN5WyFMcA==,iv:jxHY+2vxwrnYHHOsh/Udsh4pyzHC+EKY5Dl45ZSabXM=,tag:u1y1Qxch6pBDuD3QtUA33g==,type:str]
    ASSET_STORAGE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:sOvKCo/RGjYsN+X2KKI2e27hxodFfGEfOw==,iv:qkoP8IBktIz9CoYGFWRu8bPQJwY1rsurInd48FZ6BNE=,tag:jK/E1wIl3x8o7ypd316pjQ==,type:str]
    ASSET_STORAGE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1DtGAPt12DlNd1WjzRxilFptbTFZi/dl2Q==,iv:YhgOHGO4zWKXOmf2wD/h0Vm2UXHJYvILAoRt3ND1nhg=,tag:gv0Vn36bSer9qukrNC48Kw==,type:str]
    ASSET_STORAGE_S3_USE_PATH_STYLE: ENC[AES256_GCM,data:xYwuAg==,iv:PMDJa4Pic7s5WSH6BQyv98HaK3APYArW+yTEdK5ShJo=,tag:AyGLksE90qZazxG5OKMrXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMEpUQ1J6NDNiWjBpU1NL
            QnptMU0rUm93UDhUT3ZFd0VLcDdBTy85MmtzCjhCZmFXN2RNSlFUMVFmT1BMZXdR
            R0ZZbDR0QmhZYklKNENSOVdIQVZOZVUKLS0tIEFESlc1alZtMGUvNldRVytOZThv
            anpHZWx0UEhZdHhVRFIxNFVVdTVSTk0KRo5J3r3+bm6rY/SXjAXQqPk+wQeySuS8
            J7wwH/TIA8ZGjhWDFWQFSh5YWDztqnvXj9U0awhm08MWwOkaZ6jbNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T06:24:07Z"
    mac: ENC[AES256_GCM,data:VPMJeIoTc8Hd1FuoKo41M+mGfW1MSW4z/DxLzT6tuLUFBjzPL/1R6tog+EIH/Ztop7BJXKwRCpjWstoCaccDE373mlPBtq6iaCsE0t3KYoy0B788+0F6KXpvOm9j4eVlmCR8JqO8Kzg3biOFbp/2EtY3x0CGJAGvVerTYy8kbHs=,iv:D8OBM4Hy5u2yHuxzVpiq1a5mr4HPQ5OMAv7ZLncJg9s=,tag:7x6ihLlIV5SOGlpnk2E2gg==,type:str]
    version: 3.13.2
