apiVersion: v1
kind: Secret
metadata:
    name: fern
stringData:
    PUBLIC_URL: ENC[AES256_GCM,data:V5JQTMQBuRfeRdzm3ZlmkuNkMKxnzfqT,iv:qETqAEvCtyFS8eyKe+1pT4ncP2gMEaOpVmjM2oVa9O8=,tag:C4x/WgVuwAoON12avbXDuw==,type:str]
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:x99W1wHSpIwJx6V8dYx6/sln+VYbKTBkuye121+Osxdex9o5ACa5zO2KgNXJPPQcKY31BvBXQHn6jWfYwAiz6ijdlt+qyAzU,iv:9bA5E1w7krS/XwrPAGQLGk9dR5JOvL08gXmTh9OMRqA=,tag:M2kukja57n0zy617UEDzJw==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:suXY2wWn+RVhcjCb5TDXrg0fNEH3Onw1acAAiDQwIg0INa0=,iv:zUg7AaTRXg2wTK8nMCuW+GkbtXueNQZtnDs/8lWMqsM=,tag:9MFKPeQHgQ70+mWU9smV3g==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:WCLyJelJ4SrFzOl/h9oix7Y4g+luyBfTzGw=,iv:SrZLnC5vtonMKsua2RmNWMSPPmw0EfhBu4/YQez8N4Y=,tag:OMvmot1Ut3xn+8/wbI2peA==,type:str]
    EMAIL_REPLY_TO: ENC[AES256_GCM,data:mEWEjjYD/dv1+/+dqXGp7q+Bug==,iv:ubNqKKBs4VDejSTs808dKo7Qp5l4YQRIv+5xAFyPc40=,tag:UnUoPdpo1tEWzD7Z9V2mdg==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:v2uNh0xR3OKyyKsztyAAVE06Xyb4kT7MY5GWcC21K9dhrgHY,iv:qUA+AO2hS1aAV6MI8RVnl41IisGAdMArAwQSa/nv8mE=,tag:5/gc7Qix118aGBftNxXJlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWUp1RzFRbVN2VlRTSUtK
            OTJZcDJWOGI0MzIwTG5ucjdDY2FsTGI0d0R3CmxTL2FhSlc3TDRxaEQwdWEwM0Z1
            cmFucVgzaGpBdmlLWWpOdnpZY05DekEKLS0tIFRoRUsreGJ1VHNrSi9mRmtwK0xr
            cC9jemxVVUxUbjB1a29ZNnhZNWxCbzgKUWEdJ9jnhIw4bPvcI3oEgD+rHFgmL6uN
            JiA7o81PpBFW+TNmyNlcJF2GI0fB3MQ/XOopnh89wVU9A//81WdKHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:55:14Z"
    mac: ENC[AES256_GCM,data:BV8ugOpXeOHSZirZL2H67zXI2FGW9E2f+xMq4pdtFuf7yR7Rv+BvlNalR/4GGx4Ew4zVMimB5CXuRFT2Ti9WJkPkFRRFLE6FkGMMLkXtrKvVzbPIE9ahcnIKNHgYqH/evq1ZF+IAerAA0Up21DebGKwqAVsGEdFc87gWIIdPx/A=,iv:O0YM0hXG3EeEBZBMGyIkSoDnYc5MVCLvFVnCo/T3Nyk=,tag:27Ee7ThGARkqgReX0aHPLQ==,type:str]
    version: 3.13.2
