apiVersion: v1
kind: Secret
metadata:
    name: fern-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oNot8g==,iv:hl7gev+fS8vOe/Qy9JvmVVb2qjxBt/CNMA78zesU6k0=,tag:IpltTkMtV0RjxO1/m3z2eA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0+4fRhqv3wTP8r1qXdf2UqnLQPu459qPiHsarg8p,iv:mGn8asgkrzgSY5tY/OTOmp61Ii1rxRFmBtPRisLqS3Y=,tag:yxJwh/E6cDTU2/IzC9xWCA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:6kNVGg==,iv:mpoxApUmqVzDRH7s+Xh/lgr9BWBY4cYVMg+gfb6e5uA=,tag:B4aRWH3jAF2eAfYU9dq3jg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:bHsYC8dOeCj9i9xYHv6Z4XSYoFDtXoepYg==,iv:TFxciaOGgc2XZVbC4GbZ8g+8jzdf+zIlDepDxr/SwfM=,tag:kL4P320UVhm1gEZCazKmMA==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:2dEpZLk46Co=,iv:UOUegnkoh84ekaUBOsz7Qdn3xDA9sHo1Y/2xAZP4fts=,tag:Jkbzmls8d+4NU4TxwtNV/Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:41omIRk0CSo=,iv:MFFU9ml6htDlMlQM5Jf3yNhjrxqkNwYG+5vlaIaS2kU=,tag:20SWr64ER0wR2oIqdA+KIA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ud7OVC2V+b4d1Sp4xZJ0tLk9xY5FGm/FDDKXJZ0hcBRXsG5KHNZ3R83qvTjtXjVZefLBD9dgJBKmgCg7dX9J4nHQvVtf2h1YZFcdLJO7onDFHGNDnEaSIbGmS9EUOgwagfI=,iv:8oWEMMjyyFOIM8SXgsYeF7KJkjZ98BRoxqR36RIqkFw=,tag:SrgdAqBD/bnofOyMEJO7YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Ym4rcTYycTVZQ05pUjM4
            enJUVDlibWdmYW80d01SL05yajAzTTd1VmlBClZJUTVhc0pZamxGNHMvVTNpTG5i
            bC9qMEx4R3dqYUZhaTFEZThTaFZ1RE0KLS0tIDZ1cXUxUjBYd0VWNDNTekZpV2lp
            VUV0YWIzOU5ldmhLZlRycU5Sdytpb1kK2l4j3Dj4qpyxruy8ZECSicMR5rbQKXnP
            ZXDSyF4MnEy5xslUJQTeQD3lH2QPYrtc3x/WG+H7IyuuikVHiq48qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T06:16:00Z"
    mac: ENC[AES256_GCM,data:N2LzQypKz45NMmXvtlZOVrr5kZVkaElwCgQWFJ1F44cVPoEKROjg+kXzPn+5ZzGDjDNItJc7MaxRBbvyn3Y22cQC3A7APHaIpXyH1z5S19EWUz3HjVW0xstrO4GA2gQcu8sME5g/j+1OrKe9/GN4SCo9OQXKm/n8GxDyfrtixKI=,iv:N1BByffCPNndz2aCtndS9MhCfuBVPRdTQzaqJ2q4T/k=,tag:8VA2rYmJDpsjeIBuAU2XPw==,type:str]
    version: 3.13.2
