apiVersion: v1
kind: Secret
metadata:
    name: fern-paddle
stringData:
    PADDLE_ENV: ENC[AES256_GCM,data:CIQZlVhkFA==,iv:T9Pz76nQz49r92ks6G70MzVbivUOzs8ahlfytbvVYMs=,tag:6GCwWjgwskV2MYtIzW8b/Q==,type:str]
    PADDLE_API_KEY: ENC[AES256_GCM,data:ECWdUV26UuSd3WuuX5BFVhVyFa7nl3ANyfjve/tEit2nZYDFzSbkE+xPYfN8e/cl0g6hgvnLtDBeBbYyoWuEnRBrAZ11,iv:1o9pzMhzSIuIc0PpuJM6rNNcdUtQrDSxmyT6QII+enM=,tag:2cPGblzuo71yxumZIfmJ+w==,type:str]
    PADDLE_CLIENT_TOKEN: ENC[AES256_GCM,data:yINvjR3Rb/2+Bji347214Va+F7JPCvzAIXdr+GYpfiY=,iv:ao5GgNFtMOXiuU4gDMcDKRulxGiqddKIUXhO654AmGA=,tag:++aJvTVZodBGfKAhCtN+hg==,type:str]
    PADDLE_WEBHOOK_SECRET: ENC[AES256_GCM,data:1meSOMPLWiF5rHFjCLu28pSZbKhwk+TgGDVGEzbICgEtpf8RsmlFs9zXq37syBxi3fpk2yddS6Jlj3hhUQNkQyW+BZz1+Q==,iv:aAtlXyiouWrAa+N4rkoGao3L3NN40h+owyLaQfQt3X8=,tag:A8kEM/cKilMDXTu8W/qgMw==,type:str]
    PADDLE_PRO_MONTHLY_PRICE_ID: ENC[AES256_GCM,data:HJRd4G5iS1ZXnz2l9XPK2kNZKKwzobqeiaiF9D5F,iv:aMWGzVZwNQOUJ8LAwn8Fk2GQmAQ/1flkbezEymKmApg=,tag:fAhbLsE4txNIARevnUHx/g==,type:str]
    PADDLE_PRO_ANNUAL_PRICE_ID: ENC[AES256_GCM,data:9AL4U1x/KR3bs9/BMsv2ihlPFAPQCb+wHUtjN5mG,iv:2RJBsj3U/maD9+1c+3jDdiSXvKlC5NJVW/SDUW8eCy8=,tag:spOo9g1OyFkehcZUnLCVhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMnZaNjNLc3RUL2N6U1d2
            bnkycVZNRnpBWFlUTXRKTWsvYXVSSlB4Z3hjCmI5dmc1dDE5WUpyMFVUOXJnemRZ
            aWhseWQyRXk1MGVURlBhYU1hVmJRMkEKLS0tIEJ3dUdJZTd4d2N5cHNXbW96M0V6
            UzJ3YVl3d3hUR3BpVUcyTmZ6U01ZejAKEUTC0UdujmH2ah/96UwYmaOmTnxTSGKB
            NHY8BP4AVLAvw9bmIoxLupMShRY8/XpIeocaus1OV9KAYWjbD+c5NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T21:24:31Z"
    mac: ENC[AES256_GCM,data:KYNzdrqiXTElKEyO825i3+Vavr1qEJJo0m69P6IqqGnDuKyu/pNfYZ2wr8Op9c8/WD3ZvEaAHzxSO+7z4TWYrAr0zznBmn/fN/YyExYA8xOWuoVx6JNbnrp0aTwcfty2GSoemzapc3GhNJpMTyT/qPEyfSF9oQDAZLEYKCvQIqw=,iv:faf9V/KVDRrZAvOl0/8MLi7lyG0hFqGGeTPag1ecFHo=,tag:lCfTUHVud8cHbVOA11B5dA==,type:str]
    version: 3.13.2
