apiVersion: v1
kind: Secret
metadata:
    name: fern-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:818L8Yi/oKrmGA==,iv:N4FG+045Us4qx8TN7mRBVbrIonkOQXYCgMn7fU5/JwI=,tag:u3ZRuNGChk9DM/jjkx/JJQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:6Xn1ipNpG+gB8CEIAUOUWi87zzAHjXFnxQpfH+dZ,iv:SsyJsNjR2tAZNZAKXYc9e/OlOR4uLv2D0FWBRd/wH8M=,tag:ABOKSNMJLbp+miXuUtZCaw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:a/4TozzxBZdGrg==,iv:rK/110NzdgXk63gTzxa+oPDiwxix/bQgvGBhp80UlSg=,tag:sntY5mY+4wso2MDOz3pBLA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:aUL/s8Cw4jcLHws5fwcrwMOr5YHNO/XuUA==,iv:waH+i3IpThsEqilcMGhlUovGWnMUc2vKacS0gC89/Fk=,tag:xSxGS2jR42ECzfJYA8lZvg==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:gqcDVDzqKds=,iv:M4t7sTJqsVLPRzPRFILNX0zGKjcFBKy+pXlldDpK2zc=,tag:MebKRvKV666BeUYSJsAOSA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VFNPh/qaCTk=,iv:Ndja6uLtx+Np0TgzHiZaDF/PyMuHYa5MbLZcImwa8E4=,tag:Mf/Vu/u/FplsjbHPRh1/XQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:eXtVvSS0EGRcGuMrY3JlwvAl23bncy9f3tH+p0VnWJ+up6CO0S83a7XyVSJ1kOeJFhgb+DFnn3jL5ZsTj5AIQ8sZW3UKnWIow23XZg2Z3n9AA2Hinsw5w+Z72NnGQkOiD4p11Go40l8E23PV/u0=,iv:Z3oFDkq9IABavU/v52ZWIcBWwNAikyVXg/mCN42Lucw=,tag:xlM77e5lAYfyUMRQb0w+YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL2dtMDZDeVZva2RLb0ZV
            c3JDVnhyVVhJbk1jNXAwbWN6blBuWXVZMW1VCnBDeXJpZnFIOHFTekI4Wlc5aXla
            elRFUHhVamJ1Q015VmtwM1l5RUxBME0KLS0tIGZPQUJPQ25GRkJqaXQ3MldOTnV0
            a1hjS083RVcyU2xjZHpiK0RlVDIyVGMKeeNXJ/O6wDYydQ0v1ThWM2con7sU0ZvV
            s6fYj3Gp+ueIep2KPnrovvIYktpmNpPBRl2WIsZAb8ogPFBrD/7TLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:58:53Z"
    mac: ENC[AES256_GCM,data:zA8Enw+rhlN8cBAeSIo2lauNIIwLIkyfXvmjhQMxgPaJvtIdySXp3TNv90CzXRd+oshYEpcXQJbiHsCUUepYGHc9+iYXcpBJ2e2q9arZRNOJ/d7XzmDzMBfyQtEZnSLwYU1a1+jDH4+X1TOmLttjYBv3y3Zr80pcwH0zqUq4yrI=,iv:JQL6fLZOAnxz4H2f7TQii8iDUaJwQfwHdVCo8+P4gqE=,tag:TGg+ssFLK1dIO7cXJfWo1w==,type:str]
    version: 3.13.2
