apiVersion: v1
kind: Secret
metadata:
    name: rss-reader
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cCHQThIoOniDvw==,iv:yqkqD4t2LMEapFvzCWZZ9vmjDagE8ORBdjE4dNUpSPs=,tag:nZaB5pTMpQ5VcwVH5IUJMQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:RFXbQLk/DkHIu3Z4DOngRL1958K98A04+eXwBsFn,iv:ddlFe5zYDC+Cq+aCUDS35ZQ/uf7ptNLVOCaMpIid/ME=,tag:UlOJRUxBQM6oqnN4L8yVow==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:SsWh3k7DTFDfSA==,iv:0Wu6mbhmCImB6N2q0NN/Xyx6Bg8eKmB14zoqfxWj1sk=,tag:OGNps6mLTl6qQIMoRRg++A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:T4PrbmI5NbAhGXOSTKeeKIq++vqn4bpUhA==,iv:0ZP387Mo6YDpwJpveFPtxpG+WjIA/A2ns4zFEtRmrM8=,tag:H/PjkIW+XIIFU7rt3/2Ejw==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:n2bf8m/0adg=,iv:jf0x+EiqchtqzY7+gp2MN+il6mMZcdoH7ow1eHWGSGg=,tag:z676TtWsqg0U6TZ4rXHKew==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:axx+3siBVyI=,iv:5pyMfeMgrAzfNGWbS2b0jaVkPF4WbNyYqa17yELpddg=,tag:gZJKTEum8zFC1lGRy4Ri5g==,type:str]
    DB_PATH: ENC[AES256_GCM,data:0wmLMxDqIeXmnA+VFKJB9+jyIWoJCHArF+1g4R1ey/S1/JjLLvUrGRj+lQYy8fVBO64r8YSTTEqcjt5BkfERmDm9zLHj+P1JPKwP+WxoQF8KHZNUXImZq1WU0s+paCvqN3NczS3G3X/vDbdVNRg=,iv:bcwBNHsiog8+MCQeo2S9nUoGPlTpna0/Jca5nZrOqUg=,tag:3lF6NBYEQ7kRHVLi8kxs6Q==,type:str]
    BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:uhyMUjeK,iv:0FiBdhK3QMOuyoxXC1Xq/++tw8WBbjgBEGuuJmDFOzU=,tag:rBN3Y0fuWAWk4PZ/w4N1GA==,type:str]
    BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:xZ2EoX9nERt3z9MB2gI=,iv:qdhUKnUUSz/ih/4YH7Yq3ejA+38ok5eCkioXdS08OP4=,tag:/mmOrariMobIrJwE44WJkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NmZObzIrcTlXOTdsUXZR
            RDRqOXdGVUJmU0ZhVFZ2WnMzRUV2R0JKelhzCmh4N3lDTk1ETmZ6Sm9lenlRNVFJ
            RXdRcXFDa3h3a1JpSWsxK3BFRzZPLzAKLS0tIGE3Q2FDbmZiL0F2V2REWGxsOFdC
            UEl2WnJSZmtzWElhcDNOOVNReC9Pd00K++PfYMsaY4jIK/dd+ysok4J7uxndSMVC
            431YFoOo20RaH6nsRr25Y0beVQGkFLaX79Z3LBgNy1iL0YhRJSVIMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T13:17:44Z"
    mac: ENC[AES256_GCM,data:IRduAxKbVqyjjk7nZJ44tjfM7JUG7tpILUs54Mrd+4hBNqwHO5pIWk25RxLa+ve8ierd4l1uvriYYfBITvspkYvXwrSm63ywvvWTHVtCDRIlpvOk6RM0WHo60v+Mqcnw7c8OA6Kd+Y8BSphq252WHsKXhO5GO8+rpbMOqEDhb8g=,iv:DPKdLs+1yvvQWF8SBXwbbvXYO/6cHPmhygoeKgEuSLI=,tag:Uog+50V6oOZ+Q2SekvfkeA==,type:str]
    version: 3.13.2
