apiVersion: v1
kind: Secret
metadata:
    name: rss-reader
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:0CKR5SGP5dJuxw==,iv:WayjOg1T0TOzoOvDHqouoK8PhKTUHWqralYYBqFSleA=,tag:HdZJ6jCdlG9U2cYjd+fvAA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:suoUkkQTDFDIixVBI3/b2bMo12oQs0tLPsWNSTrV,iv:qlXF1Tot9/xRdYbJOEFZAnPhhAkedBjq2J3GXZT1I2Q=,tag:7QlS+1HmzDtFXoOJ7r+YzQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:H98EQMnXV1loRw==,iv:Xjgfykhkavqhsd1eqKuMXfUW7zR1Pb3wvK/RcVhpIGk=,tag:o8I7I30zattxi+ksD/DF+w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZmaICPNTbXhnn8++2P6mUTBTmFe11tlgrw==,iv:lOJELPCVZLjgoly6jgM1Is33vN4OdY7tTCj3yYBUhRQ=,tag:EXOyqtuzN4ZxUGiJS8xkmA==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:Ro8jC1J0AGM=,iv:BVM8D8tgQJx/A/MciSceTG04h5JSc/s8P9fMgHI0b30=,tag:9sLTv9WkNUOtknwyL4pjfQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3w7chWAIhL4alOJN8RneDxj/meABGoBV/kaIpM8=,iv:yvyiXgw0uqjEPxovKL2UoCwHA8Ue1b8qzv9x42/R4/U=,tag:mTgODyZOIf0G+bLTFRUW1w==,type:str]
    DB_PATH: ENC[AES256_GCM,data:sGiRgKpKGZ3BLgcs+R/grN299OuG2g/h/0iZ1UOalAhA2VuS7Xt2W2BHqZ/YQAztm6EaI08Y3j21+xJTRxk3eQaaoIbDWrG4kFrfCB+U6RMc7UombfRMzO+zs4DHk+rE10nTTZKv3Q6T4AY/5sw=,iv:xPnrxciCqx/82YNJLz3GYiFbIHKDjN3ult/WgBrwDiE=,tag:K3d7Nw847gTCoYYGTjiLdw==,type:str]
    BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:vMUbvdrl,iv:yy/M8ZHPvCvqRo5KvwU7OU5PrOyjbvY70FHYLeExouk=,tag:jyPIDtdW4htfEsOOtY1GRA==,type:str]
    BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:Tabmr4AM4GDCN7w5t4Pd5qMMJRK3YVhp,iv:JPPC4nA3waf+rTGTyczoUX9jsKbpRPqfbcenhWkqNFg=,tag:vlLPY82lOe1/KsTQUHjh6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK0dhSTdWOS9jUyszbWcr
            aTZwcFFVQkgrRTE3bEViKzZnV0xmUVZMSFgwCm1EaUt5K3N5VjdMd1ZWeXRqbURh
            akJNUGpkbVB6cmxybVU3YmFiSTZ1Y28KLS0tIEZNVXUyMWJxTmtrcDNxQThkYkFm
            OWt1ZFpXNi93UGxXc1FvSmpGcUU4elEK+otErUJZU5rIAy7naPt+HEl+/21T32Vi
            kHwnQMYtDyY8Bx5TWmRxhDcZubPwz8TJkRGRtjPIee6Ioh/6Utoj9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T13:04:35Z"
    mac: ENC[AES256_GCM,data:FRSUx3UQATraOJHeG0Dj2P8pI+gMp2bU3v7q2b0WbjdqK08171jvs5vyLRhVGVMj7OyXUXEQz+8OZXxcbP5FaVF4U6kJMWtkHHDXfwVm5+ppBpzLPbI2+X2kwK4WCrF6kn1DhB6NM2p6XGkYHpDw4TqZJO5ZtbFtCIRpaJbtPQc=,iv:iCd1EnTjM5T7c8f8TGhXjm2khhhHPcM0ODGOMOJ8mMI=,tag:TSWIFeTx38cXbiB+VneAUQ==,type:str]
    version: 3.13.2
