---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - cert-manager.yaml
  - dbms.yaml
  - forgejo.yaml
  - immich.yaml
  - kyverno.yaml
  - media.yaml
  - monitoring.yaml
  - music.yaml
  - network.yaml
  - system.yaml
  - storage.yaml
buildMetadata: [originAnnotations]
