---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/r2: enabled
spec:
  storageClassName: longhorn
  volumeName: radicale
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
