---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: smb-immich
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
