---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: media
spec:
  storageClassName: longhorn
  volumeName: seerr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
