---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.38.0
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 512Mi
      envoyService:
        externalTrafficPolicy: Local
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
