---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nepse
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          nepse:
            image:
              repository: ghcr.io/adityathebe/nepse
              tag: 0.65.3
            env:
              BACKUP_PATH: /data/backups
              LOG_LEVEL: debug
              NEPSE_CACHE_DIR: /data/cache
            envFrom:
              - secretRef:
                  name: nepse
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      main:
        controller: main
        ports:
          http:
            port: 9999
    persistence:
      data:
        existingClaim: nepse-data
        globalMounts:
          - path: /data
      dshm:
        type: emptyDir
        medium: Memory
        sizeLimit: 512Mi
        globalMounts:
          - path: /dev/shm
    route:
      main:
        hostnames:
          - 'nepse.${HOMELAB_DOMAIN}'
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: http
