apiVersion: v1
kind: Secret
metadata:
    name: npttoken
type: Opaque
stringData:
    NPT_API_KEY: ENC[AES256_GCM,data:Tx60hxRnUNmsqhKA95fYUkh+eoHJRk6+c3XAU1NrHmAbc9HKdoLZ/fK6LDBV5ZKQihURa1flXnLikTLOnkAZ/34vEIs=,iv:wquI7ibk5TV2GHZZ70OW8x4fGWx2o/N/haSFC+m1fTM=,tag:BlDVY8pf02wvKkJxy1MTWw==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VW9BWk02TENtSmlRYnlJ
            aXdZS2dQaVdRUGVGQVFzSkhZV2xUSTVpUmdzCko2WW1xa0JNUW1JK2QxWThVeFNB
            L2thK0ttalhzVk04R0JSeUQxOHBGU2sKLS0tIFY0UVZGeitJajd3dWpwaFFBcWlK
            NXBhR3E0a2tyNC9mNVhTM1JPNVR0d28KRyBQuk5r7cWjI11yNypZgA5yKccqaPXR
            1lXUSNCvX09T/REv+DiPy3TkWBq+sfCztjQPIyfNlz3KQe+cJNnFeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T15:11:31Z"
    mac: ENC[AES256_GCM,data:7Ge1A10NLbinS0MqcpFkuU0+9MAnZmdYOaXrTCbKWLBtdJmK0xrrXafUeWJ/jxtTXu9D0XhZeiGlz2WBtEk2lDLpO0DA6V+TT6JIPa9V8opOTxHKQSIG052lAnu9B4Rg4DjHj8+VW6UVHHvb0bbdFfCz/r88QgHomQZg3rmpBKY=,iv:iW4wKOqDKaJGpLCo3rdH6qyodCVJ+vopFYGgYZ88ZAE=,tag:0TdjuhFBsv8atu+gmTrRtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
