apiVersion: v1
kind: Secret
metadata:
    name: nepse
type: Opaque
stringData:
    NPT_API_KEY: ENC[AES256_GCM,data:q2VgreAsi3DmJoUOw/WZLgzdU2y2xuW6KctfhKYpTgWN4r6rrycRt4rLB8TrwE3TSRTtXH5ixF9DHniaiSfjhiDYnVw=,iv:fBAj5uYeHeMQstpSqtaJz1jc4cXKJ6reUt2P/vpruUw=,tag:YZZk8fZ+9k8t/h23Sh0c2A==,type:str]
    NEPSE_ALPHA_COOKIE: ENC[AES256_GCM,data:W0fLjDeQFYwNgZ/raYYfKAaBcSI4eKQSnxnQeE57ifNlPTScVT7KDWTwFj8kP56MF0eZkzOBuQ1SpKonCpCiqzp7MP/53Gq0m76gEfox6Zc/tjVm/XyVFgDTGUbRJezA0S1Y4dYyvHQptbl3+wchr8zGz3rgUfMbGCyf/SwnPlcwiIHFZoTtgLN77LAJVbXFq7Nxq+aOtTUNedqecghfzQVodx2pkORlv8R2r2GATB+7v0i9gFiJKXE//2qY/5YjMXDRjW3aztDzG5D9A7WImkq28Qe2dLkuB6vKAszNgeRkZXGG3Ph0vHRB7klCPGM4qLeDV7UCejXyYyi+ShMQ4p+20LZxe7CuBI3pvhErWSS0SJiawMseASfKYV3quEvmWKkgYJrt+0uFC9giq4K2PNpprvilYbm4f8P2UbwndV+bUGCl/v5ZWdbyonIMwd5y4MBNKJ+WbKNUkr9comGTvMSq0Rl5eEIGPOHbCUn4cos/guNZsXRRJgvf3mPcaRMZybvppId4LYfVO168Vbfl+sPyCeWTW6BnzbCQiIxKO7JDno7F3i/6rkj2Pj1rS05x8P46z6BT0knPUpcrXHh+mAvHiIgxJrC+1VZLOJReYz53FJuvr3dKnW2FGyMYEry1A9TUh/iRge0AZdjRGh6thyb1g54EoYYN+EC028JJqltxhWhPUEnGVAAjgKkp1JAYR5UFiGHDkukt21WodgHFl5mn2JW+qhdhtFdHiaCbgrZgn/WqSfhcM/I7qa9ARLyc1PoT/qW/p1JOm1tDgoHBZyKFHe6RoYHFRk4C6XmVCwVBniyj9c3Jptbw6wdU9IcBPuMY9QjB2hVffxnSb0pUVVjQcBdqnRlCG5DpN8v1rWXAC/8KEGsSgawUbIiRWHZEKDuXYhFueuefpHoxlbDsKHWSZ1W3f/p+IuBpjzwy7lx4klLWjxaK2f0LTznNP03zp+/DBGMrxQ0rwi2hHbp9/4n1Hxg2tpYcIbzP9DTj8KL2O6T5tIf/WICyo7Vo2Zrp4Wn5ifgC7Zem0E8Jzw9V9/ZXp3SP1LqEuDQ9esossw==,iv:jLuOL+kcYpbvs/J625IAU5ib/Bf+1ZL0RscJNx3iGIs=,tag:UZoDtqlAbNbb9tAs/p8S6w==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsekxqOVk5OHZCMzhQZEFM
            cExQR0w4Q1g4VTlxMzZzOFpYWlNUTUgxSkdvClJRdkJyOEE1T0JCMjc0TnBKOU04
            SEhpRjF2YkVUY0owMExvb0Ewb0k2Z3cKLS0tIFFTQ0F1Y0I4bUIxSTFzOFRid056
            aWNLVnZTUFhTcXlPNnFueVI3ZWw3czQKhbkztg16E+lFrZcLDSKpjHwfz2nRM5jd
            USmDoPJtJZoAx+IipMZuty1eKlW2yEymQLaMuWYnLkSRvIvFHabWng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T07:18:35Z"
    mac: ENC[AES256_GCM,data:vskI+32ByJkemJahBVVLpAYoRXmoBsrTLN4/lHPN6J9GQmlY+0oeZAJOyS2fRJJi46fiYKSk3HBu1WcNeVJ0E6I/tETKmU0OMgN6tKLmci5KffxHWCGM1XnMkgD4opT5lI7WQcTyzGFM8YQ1Mx/4SLI36iZDAoXK8YXGqWdgGWQ=,iv:a65Z5+VfiTo2vTb69lmu7NE4Lzfk769EsbjJUR0K97I=,tag:28rI4mxRUA6MHElufjeqhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
