---
apiVersion: v1
kind: Service
metadata:
  name: mc-demo-app
  namespace: mc
  labels:
    app.kubernetes.io/name: mc-demo-app
    app.kubernetes.io/part-of: mc-demo-app
spec:
  selector:
    app.kubernetes.io/name: mc-demo-app
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-demo-app
  namespace: mc
  labels:
    app.kubernetes.io/name: mc-demo-app
    app.kubernetes.io/part-of: mc-demo-app
  annotations:
    config.flanksource.com/repository: github/adityathebe/mc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mc-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mc-demo-app
        app.kubernetes.io/part-of: mc-demo-app
      annotations:
        config.flanksource.com/repository: github/adityathebe/mc-demo
    spec:
      containers:
        - name: app
          image: ghcr.io/adityathebe/mc-demo:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: demo-dbms
                  key: url
            - name: MIGRATIONS_DIR
              value: /app/migrations
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 128Mi
