apiVersion: v1
kind: Secret
metadata:
    name: demo-dbms
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:DrhakWa6,iv:OHwWVch+M6Sviy+3GVevTG//90fuIuS/3VqBZD4/t/U=,tag:9lh/ue8u2bj76+Ej1P3GWQ==,type:str]
    url: ENC[AES256_GCM,data:IWFz6SUpSHuM0qc5FWkI9bQ5EYpVhgMjGGIVeuWFCFBuuEivYFWpEeOo9fQBu8uN9qK3HmIhFZTR3DOesbICO1hjsCkUnrlTg0O+4F2nwPJiJMoGwQ==,iv:r9LbHv6npn0pvKhn8BIs4eFch3lkbFzwuA48uPcfFjs=,tag:PiXA31ypbsDxlRK/e8Lyjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc1VidEtUWXRjc1JNdEFR
            Y09rMzlpWWNTU3BwUnJpaS9FYWptOG54WmpjCmVvSXdlbHVLU3l2dytkeFNJY0Z0
            TmJFN3laOE9GUXRHRWhBRDNvTFdKZVkKLS0tIDNIcENJREdBbkZWRXI1QmdOWjJt
            UTNiKys1UHYwRGg2ekIvU2hZWEVOc0EKtZdapHNCCGuSpI1OihwFCz4QVqTSTUwB
            zuwHvk3OPxHsiqKbHBNJb9RNXAdW3JcjVusaaB5+gTUMNOhxnXvuiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T05:31:03Z"
    mac: ENC[AES256_GCM,data:KuR0nr8U0P1bDbZ5RTOIgWH7sd5O6BHbubNj6523hPE82LoNTnQ4cmmKhsetZnqnAUAdfNIjOiyIuO4TvLkRwIRcgHizx+kKTlKCm2/2TaDB5iAH2LWRRIYAVZv9vgcfTy8I9SJpJbr3tRpx++JjUdZ+b9ZG20iqNEP0Bzio1Oc=,iv:9uEsLethCCJqLs4BgrVzr7tMXn63PByhdJReHT6jLpI=,tag:Mg8+R7SEpJOOmajlqoVemg==,type:str]
    version: 3.13.3
