---
apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: agent-sandbox
spec:
  podTemplate:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: agent
          image: adityathebe/pi-coding-agent:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 5
