apiVersion: v1
kind: Secret
metadata:
    name: apikeys
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:aUFzNDdMmX+iJZtcXupemJc1h0zqvXwDOgQ74+KYJo9ea+dkWlWl5/IrgOZRbCla6wFSpwwi5vHa53yc0fp+FHROqVl1pS/AvA==,iv:nIxLr3faTW+v0q5I1o0jirgwd3s8nZXwy71LdiNN4U0=,tag:vz5IeeCeIpoHOJFdV+eMyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZUxERGhTb1I0L0MyTWw5
            cTdjU2NpNTJYUEJBTG9FU3BHOHlWQzRaN0JZCmpRb2wvdm1uWElHaDFnQXNnTU42
            Y01uTlFxbG12ZzdiMXVZdWk2bkhSL3cKLS0tIGJWRG05TXA5czNTaVVMQy9qWWVC
            M25YM1N3aVAzUzFLMHB4YW1mRmpDYkEKV5FbGIYKLUpBZ9Ayoe6C9FWsSiXhbNPU
            AqC5pzI+LTKaknDs+C9DoVtlQAJJDfnou3VKiRy+xhZfrjO+p1FWpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T16:09:51Z"
    mac: ENC[AES256_GCM,data:7PffKrA5i4OCbd4PfRqYlaT/8r4sCvs52Duno0pplagbeJzjJ5y6OmlLc2qiXInux1qzZ6Sq5CtxrAB0u1jkGWBv5jATbTEkJ40nARxLAPfoDlVe8i4wyy0Xu0Gw1AzRJePXK21UH0XdWKeogU583yvBdVdr7JzkzUiAsJMnaWc=,iv:CE1iO4TzpuuHakNvUAXrrHgahEr/Kh/NDBqTRi34mMA=,tag:kFvIFBgFVjyI/yZKe8/sAA==,type:str]
    version: 3.13.2
