# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"
    fullnameOverride: victoria-logs
    server:
      persistentVolume:
        enabled: true
        storageClassName: longhorn
        size: 20Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
      retentionPeriod: 14d
      serviceMonitor:
        enabled: true
