---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-logs-restored-20260828
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: victoria-logs-restored-20260828
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-logs-restored
  namespace: monitoring
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/r2: enabled
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  volumeName: victoria-logs-restored-20260828
  resources:
    requests:
      storage: 20Gi
