apiVersion: v1
kind: Secret
metadata:
    name: lubelogger
    namespace: productivity
type: Opaque
stringData:
    POSTGRES_CONNECTION: ENC[AES256_GCM,data:mvQ7G8fa32qOLQK5qBfvdLz+G8REc2CetvtmW4KNM6BqguxdO3v6jCUA6cx4XG/NkGd76fKcMrlXULDFIJscLZcu15gZU1r/0Ya/0CmsSpXfHuL9tu210ytk0qlb4cs=,iv:zT4UofwLOLqqDghs6+uG9Z5eQUNIvpbMoG/qtXpcLn8=,tag:rEzfVlaR0nuwvx05A1IOxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbjBmWi9NbFIvcHkwYzhI
            STF4eXhVc0FRVVlBekU2ekw4bUVlSGhHUTBZCjBiL3lLNEtoQlQ2dDFsd1M2ekpr
            ZERPSWsrYng3cUMrMFdCdXpIYmJvYVEKLS0tIFY1d1p3M1hSV1daUEpuQVJJL0NF
            MlgxcWR3bkhFVVg3cE9iTGp0U3VtUmMKF5AI5zJPy3+Yg478+7hoRdqn5axxLhid
            /907iVl6ssU5+gWIWzbW6MZ8d5atWRZ7NiGxptmByTzgWm4AAL+OyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T13:42:04Z"
    mac: ENC[AES256_GCM,data:/o2p9pT76ofDEwFnAqEIKc1Maj+FAn1fsROa81PSh2yBdahzWgXIKDh3TIQhcDva51JMRRwN9VZg6TrIdK4JOi244d0SH/Al4J6zXgsqoL966b+3vNdg8g4v/lTQ8krSMQ6UHDObmrt2LcsejdbggEGQZhVy53IBJdH/OFlIBjk=,iv:GpOF5nHXA51xr+QaW2rTu7lhqBlWirGAnq8XZsDDEWI=,tag:iut5ranC9PqZjcptJ8vExQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
