---
- name: install vim
  apt:
    name: vim
    state: present

- name: ensure vim config directories exist
  become: false
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - ~/.vim
    - ~/.vim/backupf
    - ~/.vim/backup

- name: copy vimrc
  become: false
  copy:
    src: .vimrc
    dest: ~/.vim/vimrc
    mode: '0644'
