apiVersion: v1
kind: Secret
metadata:
    name: aws-personal
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ELXDCdxbn5f7opnsiD0c26bMknk=,iv:nH9zuyF9A6SmuJf1ax2qSPm/FeqwyYUWvxoBxqzmcz4=,tag:gAJdKiuthS6MXPrYLd+YNw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VMnOKf/Xk+CC/FIZ6R8Adz4zjfBwQWG86BVaecDMn21kOBtyDTliyg==,iv:yQxf80oYc7NQob2fenb+9xeTHgmkN2JX+3fqBHN3F/Q=,tag:aVv3Oesyof/zkHFbjd82Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU0xrUlh3SWlxOFFqN1Fo
            ZU04RE12ZzJRa1Zja3NoTWFNTy91a0JSTUFJCktxOTh0T1IzL1RUMEJnbWYyVFhT
            UTBhTVFlWUJqZ2lwUTBQa1pML2xpdWMKLS0tIDlVUUFjWkZnempiKzRTMmRPR0Jr
            eDJRdnFsSVBKM3JmV3M4eUJXcTVXeHcKwFwQi3knHbwWarvXkELJWp51vHMAfo17
            9gVuWlFyERlq1v/q41pvPuF55VqA05FHwCzxWInradfMT2n3mfhUwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:33:00Z"
    mac: ENC[AES256_GCM,data:+RMoXpkUrhKlAeb7DRHI75GtFGeUu7zqhlHroIwP4x1dnxZ3RQiLdKeF7idkq1qRpkfxbzPdHron3HwSCZ9MyfjWetn7/+7kA8pghgBMpRInPdbo8VHRF5+fYHv3mc/UWfyh49Ui+mqh3N+8XIJyXl6+QVxAv90jG85V8owg8fI=,iv:CTb8ZR08D5iHzjNo2yHkcGL2E9XzJjRUOpRHztJrNZ8=,tag:9albGeNJiK9o0p73vCPXAg==,type:str]
    version: 3.13.3
