apiVersion: configs.flanksource.com/v1
kind: ScrapeConfig
metadata:
  name: adityathebe-github
  namespace: mc
spec:
  schedule: '@every 5m'
  github:
    - personalAccessToken:
        valueFrom:
          secretKeyRef:
            name: mc-secrets
            key: GH_TOKEN
      repositories:
        - owner: adityathebe
          repo: '*'
