apiVersion: v1
kind: Secret
metadata:
    name: mc-secrets
type: Opaque
stringData:
    GH_TOKEN: ENC[AES256_GCM,data:mRwMNIEdzhezQN8U4c4/iyCrXR/HUTPhgq+BDacG4UB+c1l6QXDzXgO3pZBXHel13AVvYKDjDKL8ENOmtCT3SOZOcfGW1am7RPmU3jXwspnY8CxipMF7PKREjA6L,iv:rDSffxgf163oxXvJ5RsKELgvlQ6fiL0yQGiwiwTS3Cg=,tag:AYf6M2ODS1997pVGh48j6Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:7SCGmyGG8OUCRzZsDlCgxf51FfFtYGtf2LSJls12GQO1zo/2U6s7MXM2er0iqjsAvU1IDI3TppfGV3XXigIlG15B/AocuTTf3yqpOe5VlH08oM5GLBb+HQj6uJ8jAgwzrGv5th2tNsHx9/JJcxSs2LkRqhDI8FXyACqHO3TYnnvZ6JbNTQq4IIoaQB+vc7rdFrNfo5LEaehWQc81/ABKDgxh3c8=,iv:z9o7u/zxVOx/jU8Cf5/xccV/HRYQogotkD5G3dGvSRE=,tag:njea8HyquutnJlr3U2p/7A==,type:str]
    VERSITY_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0mfPX5PvkBabIXD7JDracgBxcH0B3JUDgA==,iv:ffHX+wrxqliC80gcd9O4xNCTf+S/RjK+d0H8guPjXYc=,tag:Ut21bzeCsFG6EyTOIYEOZw==,type:str]
    VERSITY_ACCESS_KEY_ID: ENC[AES256_GCM,data:mfZZvQNkd0JNdUY3Vfej1TmxdTUMPA6gVA==,iv:N4gFQBoS2Tndmg5MZ1zyKQkI1Qzww8wmENF7a+Wa5HM=,tag:LHcn+GRNF3WDGJ3Mzqt18w==,type:str]
    VERSITY_ENDPOINT: ENC[AES256_GCM,data:g6U49ie0GjgGvLHCQT7O4dYozLtP7k8Dlw==,iv:gObUz1tQ4HnxNdQZncmunZspIG6rMAsdlcUHyVxOLxY=,tag:I8q6A5Ko8S09BOftbHMmdw==,type:str]
    VERSITY_REGION: ENC[AES256_GCM,data:5EqZxFcSqQck,iv:Kv+M8rBCWTofx/IpFD2QH+M2t4KCe50Wwo5OqJF32/A=,tag:8PIQ4bL8mtX2YIMDQsmqXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dHMyQlNjTzZES3FudlpM
            K0pzRXlJcUQwZUNZNzlUVGdHSWJRT3luMGlBCjlEUFlVUUQ1bExBR0x3NjhMVkQr
            bWEyN2xtSDhGRmpmeTNxZ1poODFhL00KLS0tIGU1eDMvYkl2dWhSOUs1NE9kcEVs
            L2I0VTBUd0thRG9RVUNjMys0RlpycWcK+rxIrpvw1O8T+qZ7i0N6bS7SIXz/LvW0
            JDlyctHDzkkE3Ii54l/xG0oT765V3GlnPBSO0Um2NEUWMvWKJ7B8Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:40:47Z"
    mac: ENC[AES256_GCM,data:EX7+JvRHUT24OYf695nWUm2u05U8yFeg5J2r79LxhbrgJfY0IKBAtj/lgHkPXsZbcPzAVqWMU+1EoXh8XT9uJRa1qUPkHyZvNtHyulUnoWvlkrhizygTDuIQUAzBvjaxnKi5ZomnePxWLwiq5IptDg1ehU35HBdntN/GWDOhOAU=,iv:pEP3E0vrDRTvxfGY9j5mlKODZBKNDGNsxBX/Tbhv0yQ=,tag:1dhc78+9IL6EKxL6EZ+80A==,type:str]
    version: 3.13.3
