apiVersion: v1
kind: Secret
metadata:
    name: aditya-gh-token
type: Opaque
stringData:
    GH_TOKEN: ENC[AES256_GCM,data:HHmgtWYQhNHdEAyfGll/frQW9975Oh8VaAB97NDfBsQD/RKCmCfecAqgYwCz/Y/FXATdR8wRJ6P5lbLHps5+lgRbBUwqIam6D2x3pVdJBjn4YYDan+XHaN8XlWdG,iv:V+mfBCABadI/LzzUPegWTPPT7ezZCn3jQtbDhHYKxkw=,tag:5tKvdu/sAbKtgRwnr4pXOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRFRNc2oxWXQ3OS8zVGVS
            MUFtUFhWYmlvc0dwTFhGemIyeG1HbURPcFQ0Clp2OXdCVXpKeUYwaDE0RHZiZDZk
            ZlFpM0RndllNYWhWUnBXQ2xYUlFsVTAKLS0tIHBFelVIMVRQNUJORW5HU2lZQTJw
            TXExQ0pvNUJtcVJQUnBhb1lxU200K2MK6GtMEFSVnrJ+kZCrSlhak1aVMkEkykFN
            mgUpeKBjz9xaZMXub+ZtqDGVrhmhxB4fMBzP7++/jqOtx/36vqwqZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T17:52:07Z"
    mac: ENC[AES256_GCM,data:v4Tae8q2OV4cFi6dNW+fe6aOINwyZHCuC1/HVGjk7YRct801as4BUJtUjTP/WdbdFI9lxpmMxDCFK7h47P6mnb2tWLSawg6l8HdTTZncJ3lumnlya+is7BU9COWRohfQHLPLVZdHbu0gyvUJLVFUioyviAoXf75UGaOB3S6D5n0=,iv:jMEeqjoQD00Ilhw/MD//mHRpFhOXXlbTG9ma+kTxAvQ=,tag:QqgX2cZnolDNmLiLTR2w1Q==,type:str]
    version: 3.13.2
