apiVersion: v1
kind: Secret
metadata:
    name: mc-secrets
type: Opaque
stringData:
    GH_TOKEN: ENC[AES256_GCM,data:N7GQrddUTGo7BcFFJOSnsgLagL+/u0oXDfymbP9wDqmGN1vUv+4+3jlTwzFQLEl9eVtMg08pvMji6bR2ENzttQqZW6iIrcLdGzNzhnmoiqMgimfQpam3HfPXqMkN,iv:9EViqzn26bjXAANR95FX0CKYiRScdN3ZPbTHNRwh+94=,tag:fQ1hLZyGzdu5hEhB+XTs3Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:usimn3yvb6hrNhnqXghz+wP2aXupJ1aMKQNBdcsWoPGdOqbm/WyjKpuV2fprXT4yM3WbP9EX6rMYplvVa8UPIfLEMTqcl3SBI2U3u00SPnIIEFQurNlh24ro8H4EwR5EHemJgZmtA1eDdpKvJNHLM2p1H/nSrQ3Xm223eaACA2dEPWyqFmgW5UKc1L2zl5LWXU5meve4hd4AZ53fPbwSL3KjzW0=,iv:WAPA74oka4or6K+K6fyWzndIA3kiKEljG4jbdnT3A+o=,tag:whImVLR3ZNP+knmPOpVRdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUG5BelUzRjB2WkQzMnNE
            aGZpZmdWK2NtNmVBcXdmMUFIMGZKblVkUld3Ck1mY2lqeGhWQ01GWlVUdTI3aUR3
            SmhycEd0MG1tSDltVnRtMmc1ald6OEkKLS0tIFh5Zzh5Sldwc3gvbnIyL1RrRDdh
            WlFVYWU3dW90OUxSVWxhbWV4c25KeHcKrVqiUGj/FXXiVmqukcUD1h4N2Wl70UFM
            NtNTFMGNRqIFBFwm73F8nEjTropAFF08eD/VGeDjErkq18tySDU0VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T18:25:00Z"
    mac: ENC[AES256_GCM,data:u70AumUdO2ie3XP8mn1gKJA7MWS08IPMd2hxy5g148o2BcGy4RDAhLapAdCJ9TbcPeDnyDlabookhysvc54Q2AblNw2liOAa3ILLTAR8VmUCKc+pEm+eMOtF1YqqyZG/N13eLNMLHJUNgzQxqnGvRQ/i+TrK+V84Ozig53Q+AZw=,iv:z23PkxeJwM6XMdybn/4TuO+iVZLbRBfBE8ZzP+6C3Aw=,tag:4hZIegC1jGTj0XEltDRNUg==,type:str]
    version: 3.13.2
