apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0gkviW5BEPqkMCtjxEC1Sfh3AsyKU3LCOGQGoWI9JdZIkqHEfXqUqw==,iv:8lZBNUAONSzcxP18Msl8hOVczvsoQX5ZwtxSmE18L38=,tag:stsC8tJ+nZ0MKK9qPLQNMg==,type:str]
    uuid: ENC[AES256_GCM,data:HiHcr4otWA9wmW7YfgECF9uB8LXy8mtjnY5SEZZsb9BaWt6D,iv:gM8TnS6+944RqGMTqpx0VV7q1X1mIYiyS/HJ7hmC9/g=,tag:xMU0QJRwGbHvmV8sB//BTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR05nM2REcmZua0crYm0w
            bS85UGtVZE1WRVBJck91LzBjYm9kd2tPaHdBCjlGdnlCdjVwS1F6cXFlNExIM1kx
            Umw3SGtib1NHVWtQUGdReVBxcWVNOE0KLS0tIHh5SGI3V0Myem53ZnZyY2FIdzU1
            Ny9zbjFTR1I0ZjNMMkM0Nm1KZlkveEkKnNAuDrZqwwNNBngsN9YYoyjaKsutvFKi
            xL+8lNc8OmrfYlbiqsMjoqlonCZtbj3qmdJGmbKi0MFVldi61qBTWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T21:36:46Z"
    mac: ENC[AES256_GCM,data:fBsiuF1dfuky5lv7W8hKb/3Qgum99hHgsE9zY9x3rjo1gAf/iBOjWH2iUE7eauiTPg0prB3H4LlxJSWcH14QUCLh5BsELMCopW66lM68aLB3LBapYk0Zy2kqjnzTfMUFTOeAvT12eMkLr0DmkXaD9R8R47LD+/BmOCG1DRUOHa0=,iv:Yl7PcKmoPW2rpFJUAcdyADZEo77+oX+8Xsjh9/pFha8=,tag:r5GgKLeaG+tOcgw5n+eYnw==,type:str]
    version: 3.13.1
