apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Hr+mg//qqSk1bKWRWEXaCThZtCSB9GhQjvA57dDjQvSwR/pfU0QQxSqwqw==,iv:ee/Kgif6vIr5SN0ISwy+W7WdqW0NpE11AMGcIKam2Hc=,tag:JfZqXF3cCopMUpyriLC2QA==,type:str]
    uuid: ENC[AES256_GCM,data:e8MH5kIq3etDUUhm9vCO4ZCeCh5K95gmo+rW+IeZoWW+Usr0,iv:kaR9sAoNaLbGKl0kLmPIt0n1cmmpRUSbkXus6kxJAEw=,tag:+y3tq33KCjeHChlVI04uhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRkE1Y1N3eVNLcXJ6S0Vv
            czU3ampoZVdsT2JCdG5WQmNJcWdTWmlkNTBJCmZSSkJTUjJaanZ5VDljMm9aZzVr
            L2V0MS9WelFYdXRTcmtjdWtDUU1DUlEKLS0tIDVkSGZMRGdyQnAvRDJrMDAvSWJQ
            Q0h1YmRKOXpFYzhBdE1pUUxGWWVCZ2sKkDrGp8x840xqtHH8kw6AA2d/kFWYZZmr
            HC1YL8T+O85F10wgKB6+AL471w72I2cP58eOxevEKqG7W48ZadYSXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T21:11:59Z"
    mac: ENC[AES256_GCM,data:fOnYQ6qL1t5aq4EuMKBjVvVIRtN8sReKqEEs51GPn3jonhuCm/WDfRGnAI2PuX8h7bP/HZNCnb0Y3E4KwYHCwQ/l8p90k2ZeE+1TOGZC7qjgaa/yGShlas2uXCUH45CJQqZIP1YFc5odH+OTzbxQSR8ib/zZoeU2pqKjsAyP2kY=,iv:hlre567jbmYuA3COKkdKYvAoJrwTZNATicEawGIg/kk=,tag:/6eEX6EShgh3hhGj033MPw==,type:str]
    version: 3.13.1
