---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: longhorn-driver-deployer
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: longhorn-driver-deployer
              spec:
                template:
                  spec:
                    initContainers:
                      - name: wait-longhorn-manager
                        securityContext:
                          allowPrivilegeEscalation: false
                    containers:
                      - name: longhorn-driver-deployer
                        securityContext:
                          allowPrivilegeEscalation: false
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: longhorn-ui
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: longhorn-ui
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-ui
                        securityContext:
                          allowPrivilegeEscalation: false
          - target:
              group: batch
              version: v1
              kind: Job
              name: longhorn-pre-upgrade
            patch: |-
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: longhorn-pre-upgrade
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-pre-upgrade
                        securityContext:
                          allowPrivilegeEscalation: false
          - target:
              group: batch
              version: v1
              kind: Job
              name: longhorn-post-upgrade
            patch: |-
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: longhorn-post-upgrade
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-post-upgrade
                        securityContext:
                          allowPrivilegeEscalation: false
          - target:
              group: batch
              version: v1
              kind: Job
              name: longhorn-uninstall
            patch: |-
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: longhorn-uninstall
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-uninstall
                        securityContext:
                          allowPrivilegeEscalation: false
  values:
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    persistence:
      defaultClass: false
      defaultDataLocality: best-effort
      recurringJobSelector:
        enable: true
        jobList:
          - '{"name":"r2", "isGroup":true}'
    defaultSettings:
      defaultReplicaCount: '1'
      defaultLonghornStaticStorageClass: longhorn
      autoCleanupSystemGeneratedSnapshot: true
      snapshotDataIntegrity: enabled
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: 'true'
      snapshotDataIntegrityCronjob: '0 4 * * *'
      allowCollectingLonghornUsageMetrics: false
      logLevel: Warn
      v1DataEngine: true
      v2DataEngine: false
    defaultBackupStore:
      backupTarget: s3://longhorn@us-east-1/
      backupTargetCredentialSecret: longhorn-versitygw-backups
    longhornUI:
      replicas: 1
    metrics:
      serviceMonitor:
        enabled: true
