---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
spec:
  cron: '0 4 * * *' # Daily at 4 AM Nepal Time
  task: backup
  groups:
    - r2
  retain: 6
  concurrency: 2
  parameters:
    full-backup-interval: '6'
  labels:
    kind: daily
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-backup
spec:
  cron: '0 5 * * 6' # Weekly at 5 AM Nepal Time on Saturday
  task: backup
  groups:
    - r2
  retain: 4
  concurrency: 2
  parameters:
    full-backup-interval: '4'
  labels:
    kind: weekly
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monthly-backup
spec:
  cron: '0 6 1 * *' # Monthly at 6 AM Nepal Time on the 1st
  task: backup
  groups:
    - r2
  retain: 3
  concurrency: 2
  parameters:
    full-backup-interval: '3'
  labels:
    kind: monthly
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
spec:
  cron: '0 */6 * * *' # Every 6 hours
  task: snapshot
  groups:
    - r2
  retain: 8
  concurrency: 2
  labels:
    kind: snapshot
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: system-backup
spec:
  cron: '0 3 * * *' # Daily at 3:00 AM Nepal Time
  task: system-backup
  retain: 30
  parameters:
    volume-backup-policy: disabled
  labels:
    kind: system
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: fs-trim
spec:
  cron: '0 4,16 * * *' # Twice daily at 4 AM and 4 PM Nepal Time
  task: filesystem-trim
  groups:
    - r2
    - default
  concurrency: 2
