apiVersion: v1
kind: Secret
metadata:
    name: longhorn-versitygw-backups
    namespace: storage
stringData:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7dqfdH/PYKTXDtTFP2kwK8Fy/NRvfyRYsw==,iv:lIX1morYonheev7y4v4+R9RbTjAPxNS+0zlzacMZ20w=,tag:V9r+REGY+WYmE+Ncew4eyQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:E0GEZClhe5RM9IegVuRMqzhz+Mn2Eu3NEQ==,iv:cTlmWOJbETuDtdHiRMRJXKhUwpGFJQ69gdrkbV5oJ+s=,tag:qgggkPvPIlDrIxaaOkqAlQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:q2FKELdHmufV,iv:GFKqqQNtiGA8f3O/jriGS6J1D5kkNIORgmC2c5GSjZU=,tag:jFVwbv5gFNKMlVgqNIYA2w==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:LpwH2F2chWFZ7atUwoTW/uiopIpYfRJT2A==,iv:DsYq3TmP2teQGiZsUaUP3ODstFW6/0h29YJRutr9DhM=,tag:4qvWkCVfwcfWNhg83+Ca/A==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZk4wUFpubWNSV0VaUEM2
            NTVVRE5BOXJveG9iNU1Fd0o0Sk5xYmkzb0Q4CnYyZUplc0pEbFJEaExwWUJnVFp2
            OXg2MXI2dUQwaXRzTzBVY0h1bEN0UGcKLS0tIExLM3JhVVRZZVNYNHhGN2M0eUdS
            bDdXNlZIb2F1aEd3c2FQYmtVUTNFV0EKxUDJZ18d7e+peLb6bIGPzMtZIVDYEW+I
            ZKJyYFbdJOAZGdHx8QxMYkGNETjTHM6kwBVgpRTjDYTvTlwK8oO+hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T08:37:06Z"
    mac: ENC[AES256_GCM,data:g51LbT3m8M9wu+lgWc5X5qYZlUfM5ECaGZjoxNZgdb3nqkWAqbQXTMqSgrxMiIHQeS6fte6VSSEPm6eWbUOQxjMFMvSPU/G2O9lzptMiwFNZsgP3/aJMt1jHbMRAQvU4t9MTUSl039TRatD7IIip3z30BGYolsuW7WIHMyd3Ebw=,iv:7HXue4TDswXNg/7yPY+41KQ+tdfqkQ3YljrkCU31ecQ=,tag:g1YREWIpbHCMRVnss1lRFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
