---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: fresh-rss
        containers:
          freshrss:
            image:
              repository: freshrss/freshrss
              tag: 1.29.0@sha256:cca8988d05cd449e1c6c69405971b1e6fc2c2116ceeb45c9fa3fc33837997a75
            env:
              TZ: ${TZ}
              CRON_MIN: 18,48
              DOMAIN: 'https://rss.${HOMELAB_DOMAIN}/'
            envFrom: *envFrom
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
              limits:
                memory: 256Mi
        defaultContainerOptionsStrategy: merge
        defaultContainerOptions:
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE  # required: root needs this to chmod files owned by www-data (UID 82) on the PVC
                - FOWNER
              drop:
                - ALL
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        existingClaim: freshrss
        globalMounts:
          - path: /var/www/FreshRSS/data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      run:
        type: emptyDir
        globalMounts:
          - path: /var/run
    route:
      app:
        hostnames:
          - 'rss.${HOMELAB_DOMAIN}'
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: http
