apiVersion: v1
kind: Secret
metadata:
    name: smb-homelab
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ztC1V0MhaQ==,iv:iHDvOare4EliUZzv5CTBJ1jwB++BvfTgaff7RDW3HTo=,tag:cOjv/YI/z3Dkgz/e5uShYg==,type:str]
    password: ENC[AES256_GCM,data:Q3pJzAUTSVNzI3QNiT8=,iv:Was+Ns3sMd6HUCU6bdT/URDf+DgvZlqQqKZtzHHsHu0=,tag:vyfWWYn/gewJUp4U2xelzg==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOUxXTE9ueEdFRktaNm9S
            UEVzcGdTaXJGeG9kSWFNU09qblVLdmpvNDNvCldwS2ZMT25nNUdpQndyaXJFaGtt
            eFJwUGFFUGVpVSttUHpJMHJuSGYyOFUKLS0tIERjQ2lmNjRtakxYZXh6MEhVOUFX
            TkRnUjVkYk9SMkc3Zm5DWGRwWXNKNGsKh3NXmTltce85o5qxy8E/6uETA2+uPcqt
            7B+ZmxXcEBm/Vw3RcxdfuwhNmFPPhnDvs1g06k7BBrRlGPp07PpmEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T15:57:14Z"
    mac: ENC[AES256_GCM,data:0zu1rX4W712ETRRrZYKLGUkKZ+7FTpD8HSEjAXu2STpnlBHONEmZQrdHBEfbx6ngu1OZu0CClGBDYePQCaCxbx48WOA/mfGtKnI+r9sw6nA0+yYN5+NfkHB5Rzft7kPv64HuU3xEP/dUrIzLIjQEPKdJLlCZZ6kUXZ9E95TmTxg=,iv:slyvZoa8Gjs6d5XLShAqaYeknyoOm+3l83VJWcqcVB4=,tag:QGJpHzemU1HCUSMLPG/3XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: smb-personal
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:W5CRPQgs,iv:Fo1tiEyCiptpWe0POg5egC7KoaPORG28ELoBxE92g/Q=,tag:dDgPdAal8BTEes/PV3CrwQ==,type:str]
    password: ENC[AES256_GCM,data:ri2RAO6KeXbeJbs9PeM=,iv:AUqLV/cCAS15e0AMOKFf0na+lSfwB7Xd0GVADsvHEAI=,tag:x/v6aBzTK+/L7/kRN2pclw==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOUxXTE9ueEdFRktaNm9S
            UEVzcGdTaXJGeG9kSWFNU09qblVLdmpvNDNvCldwS2ZMT25nNUdpQndyaXJFaGtt
            eFJwUGFFUGVpVSttUHpJMHJuSGYyOFUKLS0tIERjQ2lmNjRtakxYZXh6MEhVOUFX
            TkRnUjVkYk9SMkc3Zm5DWGRwWXNKNGsKh3NXmTltce85o5qxy8E/6uETA2+uPcqt
            7B+ZmxXcEBm/Vw3RcxdfuwhNmFPPhnDvs1g06k7BBrRlGPp07PpmEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T15:57:14Z"
    mac: ENC[AES256_GCM,data:0zu1rX4W712ETRRrZYKLGUkKZ+7FTpD8HSEjAXu2STpnlBHONEmZQrdHBEfbx6ngu1OZu0CClGBDYePQCaCxbx48WOA/mfGtKnI+r9sw6nA0+yYN5+NfkHB5Rzft7kPv64HuU3xEP/dUrIzLIjQEPKdJLlCZZ6kUXZ9E95TmTxg=,iv:slyvZoa8Gjs6d5XLShAqaYeknyoOm+3l83VJWcqcVB4=,tag:QGJpHzemU1HCUSMLPG/3XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
