apiVersion: v1
kind: Secret
metadata:
    name: smb-homelab
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:7OxgsOMkrA==,iv:3DQTOQUU5fMscZVCkoBNB3z8j+nLdiUBqspcGeGNhIY=,tag:Vrc1U5OURqjQ+326d7RXyg==,type:str]
    password: ENC[AES256_GCM,data:40dqnfTESNgRWswasOM=,iv:M29v+qAjSrgAXXXBWuzq3iVYFtbN7ZkPmnoIwpP2GaU=,tag:bjhAMPiKTcbZ5y2Ea7WRPQ==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTHZOYW10RjIrZm4raGUr
            WnBaZGhkUUJneDJWekZTZ2szaGVHWjExYm1nClhDbUg3THVrNTVBMnpuQjRCZ2Mz
            SzNzclZGS1lQcThzYXJ3RmtCRURwZ3MKLS0tIDZOeWtMVHJ2Wi9NeTZxeFcyUThr
            S1FZSzJ5V05CdVNIZHl6RGY1d0xZczAKDwK/eHzrWGuo3KFLU6tgxD0Pe9wlMgHS
            JW65zJsRMJwnapA31FOcduaumUb96olwtjivpHUc5KcguZGHz+Ka5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:07:27Z"
    mac: ENC[AES256_GCM,data:y02zC4E2BgNqjecGLwVDwigst2mrOxTU5Pofsk1MBsZrCjjMzCOIVSKMnQNVSa8xD5t1tJ3ner0XdyvLxbkW4th4llKe0iW0LyHGRFuyL/gaIcZmvX9JSUCsj0mwho8qgeWnk5HtcYEANETEek+Y9/quPHt/YEXvkOqvGbWo04Q=,iv:rRSqzhXcjNAe58IfKcfcCtWi8dCpGj1xi52SBxd8+Jo=,tag:YCQmEv7nbIgG3YekUCSxvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
