apiVersion: v1
kind: Secret
metadata:
    name: adguard-sync
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:6j/2jQ==,iv:T7TbCU94h9cDcD2U2V+3+yCkSooyEp3JqNKe4/qs+BQ=,tag:gdRfVKlSzQCxnN4x5gGoeQ==,type:str]
    ORIGIN_URL: ENC[AES256_GCM,data:9tJLH6woUNd/+sb3FHLAendfjBtifg==,iv:EI7Bi7KGS4GSyGnbVtdcJDRvF7SSsBE7R6gz42aeXjw=,tag:tySXARIZb98KsVpxmfv8uA==,type:str]
    ORIGIN_USERNAME: ENC[AES256_GCM,data:rw83vWQ=,iv:zLu/m3I6ox3bkpVa4UDj6tzanWafUeC2tEAc5vM4PUI=,tag:YAKZ9uT37YeLG9XhZSjMYQ==,type:str]
    ORIGIN_PASSWORD: ENC[AES256_GCM,data:Z9VJ2DH4zTvMIJNA448=,iv:+GoRODL15XcdnzP5LXQceZqS2H7bU454oqd/miU8+Vw=,tag:UpsW4z1oPeCfyWOeAE5QcA==,type:str]
    REPLICA1_URL: ENC[AES256_GCM,data:bDQj459m036uu01vOzOtJcM=,iv:59amI+Db+uxW9IHoqHuF56NjWFqjrfEvz12gUxxhCy4=,tag:/t4X7ax546+QPuqRNFAWlQ==,type:str]
    REPLICA1_USERNAME: ENC[AES256_GCM,data:Tz1uvqQ=,iv:DD0W4puM3Op1xC1ZY+ll/cKxypbksQ8aEpD0lO5mKYI=,tag:zPXrTTnepUwkSLAv/9phUg==,type:str]
    REPLICA1_PASSWORD: ENC[AES256_GCM,data:yxbCbhlLBcQGCYGm2V0=,iv:N0yxx1ij8nTMy4FrOMZEnV+SshsrHCawIp6P2iJ+FIU=,tag:Svy9qUbLOEP2ksFpY8swoA==,type:str]
    REPLICA2_URL: ENC[AES256_GCM,data:Y2ovVoo6GY8WJcByMo+ezH2f9PN4LD5m,iv:KTLwjAMGLwt7ou8JDGZy5yYphix8/cifpyQ2GL64Aew=,tag:Ef+ekSS0DVjNfUAqklnukg==,type:str]
    REPLICA2_USERNAME: ENC[AES256_GCM,data:tMOL4wk=,iv:5asPYduC92cM1ikWhTb5CfxLFtV0QAB2hJ2Nsoyei84=,tag:Jbgl+G6Wt+vuHAOc9AEdcg==,type:str]
    REPLICA2_PASSWORD: ENC[AES256_GCM,data:UHhm3AOJ08QTJTxe5Tw=,iv:LgOB13HLJpIANqSFD18xJN1BaPUwnhTu+tnPmJ1W6WE=,tag:RaqZaHg+pjsvA4f2Kef77w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S0lEbnNXMzh5K2dsdkpU
            Um5LYnkvamZ6SW45amtYOGExbW5md01tMVhrCnFBek8xenI4UWdER1VQcjFCY3dP
            WlJsRGlEOExvaEd1VXIrSCtueTYxTHMKLS0tIDF4VVM4c25mRzNieUY1TVg1RHFM
            ZDlkUkNYWFVCeWppclo3U1RRck1raVEKyqwI3NQEJg8TNEQHlv2gU63g92epoONJ
            VP0vRqG2/vxwb4izNaCRqnnqBelwqRbxSXhuXEdgQ6vk9Naf+DxvkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T21:20:23Z"
    mac: ENC[AES256_GCM,data:EeV5tAsDsIjy18eWSvaSMzYGtAvK/v7b+O5qIjzlAqQBot3p4b4c3s86ZO3VJFrGUel4+9epaTDtZsM5CbAG0Bl4ktPpcF45lxrlC1I4QP5AmhtFudK7mcLVu8VveMGnHu3alo5QlZmbyd4XDQxQSpDwm7eJH+VLJYF5ckquQBI=,iv:tQVoUMKkNIrYvLTVFo44OW7L0xuyi4xf1oNJVnEkC6o=,tag:zNn1GrZ9AKHSTeD7KeOlsw==,type:str]
    version: 3.13.1
