apiVersion: v1
kind: Secret
metadata:
    name: adguard-sync
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:pQHPsw==,iv:I0q5eKp+3Q+CcjVtZsajFkvFmPnKnqzR7+BdcQTwxJc=,tag:+PFs3bCiFsn5vKe5CYFsGg==,type:str]
    ORIGIN_URL: ENC[AES256_GCM,data:9IvbFuzewE8kVmSpKbeZ2Pq6pTCgsg==,iv:rrRGjNbZIdolunXbZlew7v1WlCDsmXRYwC3H0i+kjYg=,tag:0a3YrDxtGo5LX90qzbIXQQ==,type:str]
    ORIGIN_USERNAME: ENC[AES256_GCM,data:2Az25j4=,iv:qaI+Ed16fZ18RhwrOeD+1QJNJ5YTqLcUusMVsS6Vai8=,tag:lE6gvztWz6kyCZQ8GOtwwA==,type:str]
    ORIGIN_PASSWORD: ENC[AES256_GCM,data:6tvZKnKdL/PYkD6+6GM=,iv:+ERbng/YqsBHv30t1cz9krQCaVfPmEwx+j0IEMdkT08=,tag:0T7OmrZTPf1TL3BgIaox8w==,type:str]
    REPLICA1_URL: ENC[AES256_GCM,data:pe8/ZYDGVyCsOJYdhQuI6fpoywnCzQgw,iv:Hm82Yga/fZlFxhzGW0q6JpQW5DrgeFzUQ0+cLlqIxsc=,tag:rcRB6XgWms+5O5J5I5pAuA==,type:str]
    REPLICA1_USERNAME: ENC[AES256_GCM,data:y2p05GQ=,iv:anHkWVqq676aSZmnFQMe33xCL8eiKa4+RI4pKdtYtgw=,tag:xpLDNxa0mHzcvfRCoCjrYg==,type:str]
    REPLICA1_PASSWORD: ENC[AES256_GCM,data:2lE6XBMmHSYV7bOA4fM=,iv:O8d8NGg8EiV5QBfG5TG8doiHDCbp46J60h2wtWa0HX8=,tag:RjKV8mJxPW829v7XDFNfKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVDBrSVhRVmpVWk5mMmV4
            N0REdytEbHNpWnpJRzB3aDMxcGk0M3VwN0JBCnN6Yi92RXJSSlk4WlVSRWtESjBV
            UjdXOXA4SzUza2prRmVPRkg1OGJQbTAKLS0tIGp6eWZNV0FObFcvOUZzUkh5Y0xP
            UlpROHY2c3RjeFc5WVVqRWVHZEhQVW8KTvHtg2O+sPr8WN+9n7kO1+D4Dn++IJmV
            No4tfh34ePOrZ7td8oQ/uiRbExME6DTGRA8gO5hP7cNeeA61+y2AtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T08:53:07Z"
    mac: ENC[AES256_GCM,data:zNL5BODDqlm1n/3Zxi7he2yiIZ9ossNbRKa7CEjqlN4JJ/5BxFcOxGyHZ49jjb64VW0eUaCn3rgk18WN5qzp1L01MNYoXAoCm6GIGoW07avJlf3hF7yzHFLtFs1oZGMVo2ck4jyeh1ysTkrQQ/0EoIhvFf8BQboTq19vbNRYJzY=,iv:d5qF7wQ6k0SKZc35PRochkc8ZgNLT1cMs7bf89PeX5Q=,tag:P7L3XexAh+uYTRVdxTxnjA==,type:str]
    version: 3.13.1
