---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./disallow-host-namespaces.yaml
  - ./disallow-privilege-escalation.yaml
  - ./disallow-privileged-containers.yaml
  - ./require-drop-all.yaml
  - ./require-run-as-nonroot.yaml
