apiVersion: v1
kind: Secret
metadata:
    name: gickup-github-token
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WLracjqK4qLA0CO7LEk+++ZaOld2UVSB7NTK0oGwkoD8/UOEUutWtlu0q9Pwuwew+KEBosQZnGtI5CM87ToBslK3SACzK3bkZXFPLdbOtu0xHdLjXkA8uiCc9c9j1A==,iv:JBNoK6PRnTwlXVMo43gs8AzoLoJP4/kLdk47m6b7voU=,tag:0/Tx595YvL/ChbJtK36bOw==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdUl5dHI3RFdFalYrNXpj
            SHpRbHd2U2FBS3BJQUQ4SUVTVkpxUUtUL2dRCnY3YTRyTjdvMnFRQ3BENGpDcGs1
            cXNwTC82cmRkTmxkaUpWNm50RENlWU0KLS0tIDR2Qk9vYkJiQi9KUzlCQWNHTDNn
            Y0l6ZFBjeDA3bGluWTVOdGE3MWRlSEUKD4MFsIFFS9LSrn89bVU9joVFARpZECsu
            UyMrKVve9eRGIAU8ZJpkzEHCJXBfo7/kD/ld359ZlfSvbHbKoQ4fMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T10:38:41Z"
    mac: ENC[AES256_GCM,data:pHs1n1bIx9fqV433NmLTb4moBwm4aqWmRM8EqqHfWJuok4V8NtGgrGWp/S/dgkB8DDozbRDDRLME9mEvUqHVMXeL6JnyhyILgxcZgW80LSmGk0qPnPUXAlXW+I+ha2zg8HcNNZHwQrVpw00ZLp9MG9WFEmY7XiNyghyRXcJMKv4=,iv:ek+86DtfrY0r9uxezzVyVJ1Om4qaJbTNkfhvsRAG/Nc=,tag:JNNNRZXtDLolZLSusNo3+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
