apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:9e6Q44020pS6g8M=,iv:7HccCoMo0eZMmrkeGGEYIlJH9uHD32NQeoxaawvOll8=,tag:2sQcrfJjJfr5/XBOH5jdQg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:PctHoLzmLUg/4AwQ1RQL0o8vML0fsoA=,iv:DcafagaHkmUnfS5ojMp3sYg1hpf8tHgaAqCEX6US2I0=,tag:00GijEhrWzCR7xHzeHIejQ==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:2scqAKDkdl/u3ddZZGzK5zeCzhufR2nhY7QEj3FzsLQ=,iv:lJKk3prLIWDOO73iqZVKvx3RZaru3a++Oj8ZUgmGTx0=,tag:NZqV2Y5LAva6ZXbl5jqkuQ==,type:str]
    CF_TUNNEL_ID: ENC[AES256_GCM,data:KZEr9PxgRCpyszXL3KuT0okEaQy+ReD3lhOQEgibaHdTIjtU,iv:CPpAfMuFY2YPRuWZGEr+fwTzjGFQU2v+y+2ve49kX9o=,tag:btrR4N26qzMe2kVwfRDGFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eVhFYnI1aCtjV3hHaTRT
            ZDBOWFN0OEdpSEo5R1VwdHlpYm9weFVZVVd3CnBLRXhHR3BtMStmZGpVWXl4Tkxm
            QVR5bVpacVphVDgyZnFsaEtGZjYzN28KLS0tIDZyRG96TGxNRUZFdGxuUnkzQXIz
            bFJlTDlUak4xajRUaWU1ckc5WitESkUK/UT+/AMZN0/IPzDQZfLC7WVPyudVpa/L
            fyTbJXwSoCG0Z2WstLH7OvqTmVPokI1C8FtXcZNHEiiFc2nu9nxjdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T06:59:18Z"
    mac: ENC[AES256_GCM,data:qj2KhXHH9odQQaWDKfmgXFNErOVlXrWqrMJKo2bU3dCAnihphHSLTTDx9a7GCekpRjMcHgeoRpP34uHSQlZqm9cpt+aE++qU422WSDiB+FU9JhEn49Q8mvUgddj9qFwSSJ/EKBxq5095hJKCXOZOe5gXFYeMITyQ3qAjMaM7TxQ=,iv:V62dtvTJAS6Foh7TDvy6DgYPh8lgchlncxzi16jAq1E=,tag:9bi+6ziaaF1HQqT9qtNlfg==,type:str]
    version: 3.13.1
