apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:FoEi6d2BC4DLFku2h3Y051OCN49Fi91+mytFHX80CdEHzp7Eo6hOVKbzn5OVgreVvBqGC9oT9ZMzj7cSZtsuI0S8zgh9T8LjNKQJ3Opy/KY=,iv:s6fz9bOZbLtrnv7I5m2JGlS6JQ1+UYdq6+QbkFoqzBk=,tag:NHgHPEPppZU3gh9rDSveXw==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:1/FpTdZbG6ScDS0/237jom4B3ZbI9yA=,iv:PfqI858QubL0boI/HppHxTc971K0G+3rZWKbqhx736w=,tag:auZt7XxUBIjd5baX1y1YAg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:KoENbGbUO9zlDotUTxq8I0yqEe0Pt/3k,iv:AfdUTOmb74LliuyI1fhlz3tbmCASKkDhetfZBRaVTbk=,tag:BmrmOwdN0GGJ8vh4AtS9UA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:yI4AZ82KFrodErbM8o3cMg==,iv:iAmtYWr5UtEMvhAIpddlyD9BnLz1/epsU/DWt3sklC8=,tag:QxTFBHhim41ArLyAI0sqAQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:cObnJKFbvRCV,iv:KUSGfXUInwQBm4sf+wJzQRyo5CivYmLJS7JKDPTNxJc=,tag:3sIuC8qSzdrrAJpEyspXMQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:6EDy239vhvkl,iv:SJO2bmKv2PyLGiM3SZnrndL8r1i87AtuaUjGzjFPbuE=,tag:D1dIePSWIJGzLJqdIGUw0g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:bx0GIS2iO8iqHvJUzcd9euEQwTLp8XY7,iv:0c8sM4/OKWYqnRn/cLBA+b0t2S5KmixqIzQ9cSoPJSE=,tag:H95hFq8eS7OOW/9PzGswWg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:7ZVWEemqr/zy,iv:n4ZCXvAA7S6GUgppt3tw59b7VT08nHYZvJ0fIFPI5gI=,tag:zz4dBwWgpMOjnNsPgjhMKg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Pg71qKVSJFkZVEanpmq6Bg==,iv:rDySb4FVpFsR6OYgt1Rm+ZcOogqkL6wUe+PtlFP3Gw4=,tag:qwktb2VHbBoGrQloapSqxg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Xm1/ODSqEuxl,iv:DRvQtM2hxRzmMHC3k6HLFWFY3M3/CvdExENMXjsWW9A=,tag:6gM12mypaBPXlh21Ww8iOQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Sv/Z0Ah+2f2LskQIhXob5s+XCneiSYQ/,iv:Bt3R8zPTgsi6wpJLzYNKZqckOwswB4oVnBWy+UDHyOk=,tag:CwW2YEF10Zf3VU3ThXQxFA==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:p/yqDYlX2Lg=,iv:YHnX/inZx4GCiLU3ZHkgEIauroQiBTpVLilSfI7jVns=,tag:PblrtA6ReuHipf8qAHDO+Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0R8op/GzD1w=,iv:1IqDQ2RXgPi4y8HrciYnmeeIjTyeESvtpLQ9qnOXsQM=,tag:OroqibFmguak5wGEUItaWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aUNLdFltazM1aXVKTm5N
            ckpQbituTTRvV1MyWlZrUE9zbHZqRkY1RTFrCkdJMFptS0tsQlVHNU1DdTdvMGtV
            dU5WMjdkOFhxczd4YXJHOVhCZU5QejgKLS0tIFErU1dNcUY5TGpkV3FEOVRQMWsz
            NUxaZ2pyZitCZmxTdkUvSm4waTYyRFUKryIvvUKHgzvFqVe/ZijNL8X/uyMtHFcH
            /eHbjbuvK8FoFxxlMPQfkVALeE0lEYY9bpHUcdCqbGDYJcfZ902QWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T09:41:36Z"
    mac: ENC[AES256_GCM,data:SaXgP/1inye+s2TT8EQKtGIZpFX7trUGMWyydqjiMgTtEJgnOpxNJzd6L/AooF/FmmZwCq2I3dsiljntCvVHHNddbUSMZpzBp1J/Q76ntjkrB2LDYJwvalUcUoN6XmGPnGmvgCID1nshg70JF+bUeRgLdo3bdJ5LJrGPyDLBNfU=,iv:POHtN384eIfg45a9oAvYu46oBpchPLjqPsjzzAb17s4=,tag:gf87zSKRPZcGlnG1DB8TqA==,type:str]
    version: 3.13.1
